lms/urls.py
from django.conf import settings
from django.conf.urls import url # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (
    # create_students,
    # delete_student,
    # edit_student,

    StudentCreateView,
    StudentDeleteView,
    StudentListView,
    StudentUpdateView,
    generate_students

)

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('generate/', generate_students, name='generate'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid_code>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid_code>', StudentDeleteView.as_view(), name='delete'),
]

students/models.py
import datetime # noqa
import random
import uuid

from core.models import Person

from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from faker import Faker

from groups.models import Group


class Student(Person):
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    rating = models.SmallIntegerField(null=True, default=0)
    phone_number = models.CharField(null=True, blank=True, max_length=20)
    uuid_code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return f'{super().__str__()}, Rating: {self.rating}'

    def save(self, *args, **kwargs):

        phone_number = self.phone_number
        if phone_number is not None:
            phone_number = str(phone_number)
            if not phone_number.isdigit():
                raise ValidationError("Write int format")

        super().save(*args, **kwargs)

    @classmethod
    def create_student(cls):
        fake = Faker()

        first_name = fake.first_name()
        last_name = fake.last_name()
        birthdate = fake.date_of_birth()
        rating = random.randint(0, 100)
        groups = Group.objects.only('id').all()
        random_group = random.choice(groups)
        student = Student.objects.create(
            first_name=first_name,
            last_name=last_name,
            birthdate=birthdate,
            rating=rating,
            group=random_group)
        return student

students/forms.py
from django import forms
from django.core.exceptions import ValidationError # noqa

from students.models import Student


class StudentBaseForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'phone_number', 'rating', 'group']

    # def clean_phone_number(self):
    #     phone_number = self.cleaned_data['phone_number']
    #     phone_number = str(phone_number)
    #     if not phone_number.isdigit():
    #         raise ValidationError("Write int format")
    #     return phone_number


class StudentCreateForm(StudentBaseForm):
    class Meta(StudentBaseForm.Meta):
        fields = ['first_name', 'last_name', 'phone_number', 'rating', 'group']


class StudentEditForm(StudentBaseForm):
    class Meta(StudentBaseForm.Meta):
        fields = ['first_name', 'last_name', 'phone_number', 'rating', 'group']

students/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect # noqa
from django.shortcuts import get_object_or_404, render # noqa
from django.urls import reverse, reverse_lazy # noqa
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from students.forms import StudentCreateForm, StudentEditForm
from students.models import Student
from students.utils import create_random_students, format_list, gen_password, parse_count, parse_length
# Create your views here.


def hello(request):
    return HttpResponse('Hello from Django!')


def get_random(request):
    try:
        length = parse_length(request, 10)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)

    result = gen_password(length)

    return HttpResponse(result)


def generate_students(request):
    try:
        count = parse_count(request)
    except Exception as ex:
        return HttpResponse(str(ex), status=400)

    result = create_random_students(count)

    return HttpResponse(format_list(result))


# def get_students(request):
#     students = Student.objects.select_related('group').all()
#
#     params = [
#         'first_name',
#         'last_name',
#         'rating',
#         'rating__gt',
#         'rating__lt',
#     ]
#
#     for param in params:
#         value = request.GET.get(param)
#         if value:
#             students = students.filter(**{param: value})
#
#     return render(
#         request=request,
#         template_name='students.html',
#         context={
#             'students': students,
#
#         }
#     )


# def create_students(request):
#
#     if request.method == 'GET':
#
#         form = StudentCreateForm()
#
#     elif request.method == 'POST':
#
#         form = StudentCreateForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('students:list'))
#
#     return render(
#         request=request,
#         template_name='students_create.html',
#         context={
#             'form': form,
#
#         }
#     )


# def edit_student(request, uuid_code):
#     try:
#         student = Student.objects.get(uuid_code=uuid_code)
#     except Student.DoesNotExist:
#         return HttpResponse("Students doesn't exist", status=404)
#
#     if request.method == 'GET':
#
#         form = StudentEditForm(instance=student)
#
#     if request.method == 'POST':
#
#         form = StudentEditForm(
#             data=request.POST,
#             instance=student
#         )
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('students:list'))
#
#     return render(
#         request=request,
#         template_name='students_edit.html',
#         context={
#             'form': form,
#             'student': student,
#
#         }
#     )


# def delete_student(request, uuid_code):
#     # try:
#     #     student = Student.objects.get(uuid_code=uuid_code)
#     # except Student.DoesNotExist:
#     #     return HttpResponse("Students doesn't exist", status=404)
#
#     student = get_object_or_404(Student, uuid_code=uuid_code)
#
#     student.delete()
#     return HttpResponseRedirect(reverse('students:list'))


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentEditForm
    template_name = 'students_edit.html'
    success_url = reverse_lazy('students:list')
    context_object_name = 'student'
    pk_url_kwarg = 'uuid_code'

    def get_object(self):
        uuid_code = self.kwargs.get('uuid_code')
        return self.get_queryset().get(uuid_code=uuid_code)

    def form_valid(self, form):
        result = super().form_valid(form)
        request = self.request
        messages.success(request, 'Student successfully updated')
        return result


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentCreateForm
    template_name = 'students_create.html'
    success_url = reverse_lazy('students:list')

    def form_valid(self, form):
        result = super().form_valid(form)
        request = self.request
        messages.success(request, 'Student successfully created')
        return result


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'students.html'
    context_object_name = 'students'
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.select_related('group').all()
        request = self.request

        params = [
            'first_name',
            'last_name',
            'rating',
            'rating__gt',
            'rating__lt',
        ]

        for param in params:
            value = request.GET.get(param)
            if value:
                qs = qs.filter(**{param: value})

        return qs


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('students:list')
    pk_url_kwarg = 'id'

    def get_object(self):
        uuid_code = self.kwargs.get('uuid_code')
        request = self.request
        messages.success(request, 'Student successfully deleted')
        return self.get_queryset().get(uuid_code=uuid_code)

students/templates/students.html
{% extends 'base.html' %}

{% block title %}
    <title> Student list </title>
{% endblock  %}

{% block subheader %}
<header>Filter students</header>
{% endblock  %}

{% block content %}
    <form>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">First name:</span>
            </div>
            <input type="text" class="form-control" placeholder="Enter first name" name="first_name"
                   aria-label="Username" aria-describedby="addon-wrapping">
        </div>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">Last name:</span>
            </div>
            <input type="text" class="form-control" placeholder="Enter last name" name="last_name" aria-label="Username"
                   aria-describedby="addon-wrapping">
        </div>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">Rating:</span>
            </div>
            <input type="number" class="form-control" placeholder="Enter rating" name="rating" aria-label="Username"
                   aria-describedby="addon-wrapping">
        </div>

      <input type="button" class="btn btn-outline-dark" value="Create" onClick='location.href="{% url 'students:create' %}"'/>
      <input type="button" class="btn btn-outline-dark" value="Generate" onClick='location.href="{% url 'students:generate' %}"'/>
      <input type="submit" class="btn btn-outline-dark" value="Search"><p><hr>

        <h5>All list of students: </h5><p>

    </form>

<!--{{students|safe}}-->

{% include 'includes/students-table.html' %}

{% endblock %}

students/templates/students_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title> Create student </title>
{% endblock  %}


{% block subheader %}
<header>Create students</header>
{% endblock  %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="button" class="btn btn-outline-dark" value="List of students" onClick='location.href="{% url 'students:list' %}"'/>
        <input type="submit" class="btn btn-outline-dark" value="Create">
    </form>
{% endblock %}

students/templates/students_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title> Edit student </title>
{% endblock  %}


{% block subheader %}
<header>Edit students</header>
{% endblock  %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="button" class="btn btn-outline-dark" value="List of students" onClick='location.href="{% url 'students:list' %}"'/>
        <input class="btn btn-outline-dark" formaction="{% url 'students:delete' student.uuid_code %}" type="submit" value="Delete">
        <input class="btn btn-outline-dark" type="submit" value="Save">
    </form>
{% endblock %}