groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls import url # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

groups/models.py
import datetime
import random

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

import students.models # noqa

from teachers.models import Teacher


class Classroom(models.Model):
    name = models.CharField(max_length=32)
    floor = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(2), MaxValueValidator(5)]
    )

    def __str__(self):
        return f' name: {self.name};' \
               f' floor: {self.floor};'


class Group(models.Model):
    name = models.CharField(max_length=64, null=False)
    members = models.CharField(max_length=64, null=False)
    start_date = models.DateField(null=True, default=datetime.date(year=2020, month=8, day=4))
    end_date = models.DateField(null=True, default=datetime.date(year=2020, month=12, day=20))
    rating = models.IntegerField(null=True, default=0)
    teacher = models.ForeignKey(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups'
    )
    curator = models.OneToOneField(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='curated_group'
    )
    headman = models.OneToOneField(
        to='students.Student',
        null=True,
        on_delete=models.SET_NULL,
        related_name='handled_group'
    )
    classrooms = models.ManyToManyField(
        to=Classroom,
        related_name='groups'
    )

    def __str__(self):
        return f'{self.id}) ' \
               f'Group name: {self.name};'
        # f' Members: {self.members}; ' \
        # f'Group start: {self.start_date};' \
        # f'Group end: {self.end_date};' \
        # f' Rating: {self.rating}'

    @classmethod
    def create_group(cls):
        course_list = [
            'Python for beginner',
            'Advanced python',
            'Python for ML',
            'Python for web',
            'Python for games',
            'Python for data science',
            'Python for hacking'
        ]
        name = random.choice(course_list)
        rating = random.randint(0, 100)
        teachers = Teacher.objects.only('id').all()
        random_teacher = random.choice(teachers)
        group = Group.objects.create(name=name, rating=rating, teacher=random_teacher)
        return group

    def clean_headman(self):
        headman = self.headman
        group = self.students.all()
        if headman in group:
            return headman
        else:
            raise ValidationError('Headman from another group')

    def save(self, *args, **kwargs):
        self.clean_headman()

        super().save(*args, **kwargs)

groups/forms.py
from django import forms
from django.core.exceptions import ValidationError # noqa

from groups.models import Group


class GroupBaseForm(forms.ModelForm):
    class Meta:
        model = Group
        # fields = ['name', 'members', 'rating', 'teacher', 'headman']
        fields = '__all__'
        exclude = ['start_date', 'end_date']


class GroupCreateForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        fields = '__all__'
        exclude = ['start_date', 'end_date']


class GroupEditForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        fields = '__all__'
        exclude = ['start_date', 'end_date']

groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect # noqa
from django.shortcuts import get_object_or_404, render # noqa
from django.urls import reverse, reverse_lazy # noqa
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from groups.forms import GroupCreateForm, GroupEditForm
from groups.models import Group
from students.utils import format_list # noqa


# def get_groups(request):
#     groups = Group.objects.select_related('teacher').all()
#
#     params = [
#         'name',
#         'members',
#         'rating',
#     ]
#
#     for param in params:
#         value = request.GET.get(param)
#         if value:
#             groups = groups.filter(**{param: value})
#
#     return render(
#         request=request,
#         template_name='groups.html',
#         context={
#             'groups': groups
#         }
#     )
#
#
# def create_groups(request):
#
#     if request.method == 'GET':
#
#         form = GroupCreateForm()
#
#     elif request.method == 'POST':
#
#         form = GroupCreateForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('groups:list'))
#
#     return render(
#         request=request,
#         template_name='group_create.html',
#         context={
#             'form': form
#         }
#     )
#
#
# def edit_groups(request, id): # noqa
#     try:
#         group = Group.objects.get(id=id)
#     except Group.DoesNotExist:
#         return HttpResponse("Groups doesn't exist", status=404)
#
#     if request.method == 'GET':
#
#         form = GroupCreateForm(instance=group)
#
#     if request.method == 'POST':
#
#         form = GroupCreateForm(
#             data=request.POST,
#             instance=group
#         )
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('groups:list'))
#
#     return render(
#         request=request,
#         template_name='group_edit.html',
#         context={
#             'form': form,
#             'group': group,
#             'students': group.students.all(),
#
#         }
#     )
#
#
# def delete_group(request, id): # noqa
#     group = get_object_or_404(Group, id=id)
#
#     group.delete()
#     return HttpResponseRedirect(reverse('groups:list'))


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupEditForm
    template_name = 'group_edit.html'
    success_url = reverse_lazy('groups:list')
    context_object_name = 'group'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.all()
        return context

    def form_valid(self, form):
        result = super().form_valid(form)
        request = self.request
        messages.success(request, 'Group successfully updated')
        return result


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    template_name = 'group_create.html'
    success_url = reverse_lazy('groups:list')

    def form_valid(self, form):
        result = super().form_valid(form)
        request = self.request
        messages.success(request, 'Group successfully created')
        return result


class GroupListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = 'groups.html'
    context_object_name = 'groups'
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.select_related('teacher').all()
        request = self.request

        params = [
            'name',
            'members',
            'rating',
        ]

        for param in params:
            value = request.GET.get(param)
            if value:
                qs = qs.filter(**{param: value})

        return qs


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('groups:list')
    pk_url_kwarg = 'id'

    def get_object(self):
        obj = super().get_object()
        request = self.request
        messages.success(request, 'Group successfully deleted')
        return obj

groups/templates/group_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title> Create groups </title>
{% endblock  %}


{% block subheader %}
<header>Create groups</header>
{% endblock  %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

         <input type="button" class="btn btn-outline-dark" value="List of groups" onClick='location.href="{% url 'groups:list' %}"'/>
        <input type="submit" class="btn btn-outline-dark" value="Create">
    </form>
{% endblock  %}

groups/templates/group_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title> Edit groups </title>
{% endblock  %}


{% block subheader %}
<header>Edit groups</header>
{% endblock  %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}
        <input type="button" class="btn btn-outline-dark" value="List of groups" onClick='location.href="{% url 'groups:list' %}"'/>
        <input type="button" class="btn btn-outline-dark" value="Delete" onClick='location.href="{% url 'groups:delete' group.id %}"'/>
        <input type="submit" class="btn btn-outline-dark" value="Save">
    </form>

    {% include 'includes/students-table.html' %}

{% endblock %}

groups/templates/groups.html
{% extends 'base.html' %}

{% block title %}
    <title> Groups list </title>
{% endblock  %}

{% block subheader %}
<header>Filter groups</header>
{% endblock  %}

{% block content %}
    <form>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">Group name:</span>
            </div>
            <input type="text" class="form-control" placeholder="Enter group name" name="name" aria-label="Username"
                   aria-describedby="addon-wrapping">
        </div>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">Members:</span>
            </div>
            <input type="text" class="form-control" placeholder="Enter members" name="members" aria-label="Username"
                   aria-describedby="addon-wrapping">
        </div>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">Rating:</span>
            </div>
            <input type="number" class="form-control" placeholder="Enter rating" name="rating" aria-label="Username"
                   aria-describedby="addon-wrapping">
        </div>


      <input type="button" class="btn btn-outline-dark" value="Create" onClick='location.href="{% url 'groups:create' %}"'/>

      <input type="submit" class="btn btn-outline-dark" value="Search"><p><hr>

        <h5>All list of groups: </h5><p>

    </form>

<!--{{students|safe}}-->

{% include 'includes/groups-table.html' %}

{% endblock  %}