lms/urls.py
from django.conf import settings
from django.conf.urls import url # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

teachers/urls.py
from django.urls import path

from teachers.views import TeacherCreateView,  TeacherDeleteView, TeacherListView, TeacherUpdateView

app_name = 'teachers'


urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('edit/<int:id>', TeacherUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete')
]

teachers/models.py
from core.models import Person

from django.db import models

from faker import Faker


class Teacher(Person):
    experience = models.TextField(max_length=250, null=False)
    job = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f'{super().__str__()}, ' \
               f'Experience: {self.experience};' \
               f'Place of work: {self.job}'

    @classmethod
    def create_teacher(cls):
        fake = Faker()

        first_name = fake.first_name()
        last_name = fake.last_name()
        birthdate = fake.date_of_birth()
        teacher = Teacher.objects.create(first_name=first_name, last_name=last_name, birthdate=birthdate)
        return teacher

teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherBaseForm(forms.ModelForm):
    class Meta:
        model = Teacher
        # fields = ['first_name', 'last_name', 'job']
        fields = '__all__'
        # exclude = ['job']


class TeacherCreateForm(TeacherBaseForm):
    class Meta(TeacherBaseForm.Meta):
        fields = '__all__'


class TeacherEditForm(TeacherBaseForm):
    class Meta(TeacherBaseForm.Meta):
        fields = '__all__'

teachers/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect # noqa
from django.shortcuts import get_object_or_404, render # noqa
from django.urls import reverse, reverse_lazy # noqa
from django.views.generic import CreateView, DeleteView, ListView, UpdateView


from teachers.forms import TeacherCreateForm, TeacherEditForm
from teachers.models import Teacher


# Create your views here.


# def get_teachers(request):
#     teachers = Teacher.objects.all()
#
#     params = [
#
#     ]
#
#     for param in params:
#         value = request.GET.get(param)
#         if value:
#             teachers = teachers.filter(**{param: value})
#
#     return render(
#         request=request,
#         template_name='teachers.html',
#         context={
#             'teachers': teachers
#         }
#     )
#
#
# def create_teachers(request):
#
#     if request.method == 'GET':
#
#         form = TeacherCreateForm()
#
#     elif request.method == 'POST':
#
#         form = TeacherCreateForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('teachers:list'))
#
#     return render(
#         request=request,
#         template_name='teacher_create.html',
#         context={
#             'form': form
#         }
#     )
#
#
# def edit_teachers(request, id): # noqa
#     try:
#         teacher = Teacher.objects.get(id=id)
#     except Teacher.DoesNotExist:
#         return HttpResponse("Teachers doesn't exist", status=404)
#
#     if request.method == 'GET':
#
#         form = TeacherCreateForm(instance=teacher)
#
#     if request.method == 'POST':
#
#         form = TeacherCreateForm(
#             data=request.POST,
#             instance=teacher
#         )
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('teachers:list'))
#
#     return render(
#         request=request,
#         template_name='teacher_edit.html',
#         context={
#             'form': form,
#             'teacher': teacher,
#             'groups': teacher.groups.all(),
#         }
#     )
#
#
# def delete_teacher(request, id): # noqa
#     teacher = get_object_or_404(Teacher, id=id)
#
#     teacher.delete()
#     return HttpResponseRedirect(reverse('teachers:list'))


# TODO don't show age
class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherEditForm
    template_name = 'teacher_edit.html'
    success_url = reverse_lazy('teachers:list')
    context_object_name = 'teacher'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = self.get_object().groups.all()
        return context

    def form_valid(self, form):
        result = super().form_valid(form)
        request = self.request
        messages.success(request, 'Teacher successfully updated')
        return result


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'teacher_create.html'
    success_url = reverse_lazy('teachers:list')

    def form_valid(self, form):
        result = super().form_valid(form)
        request = self.request
        messages.success(request, 'Teacher successfully created')
        return result


class TeacherListView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = 'teachers.html'
    context_object_name = 'teachers'
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        request = self.request

        params = [
            'first_name',
            'last_name',
            'age',
            'experience',
            'job',
        ]

        for param in params:
            value = request.GET.get(param)
            if value:
                qs = qs.filter(**{param: value})

        return qs


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    template_name = 'teacher_delete.html'
    success_url = reverse_lazy('teachers:list')
    pk_url_kwarg = 'id'

    def get_success_url(self):
        obj = super().get_success_url()
        request = self.request
        messages.success(request, 'Teacher successfully deleted')
        return obj

teachers/templates/teacher_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title>Create teacher</title>
{% endblock  %}


{% block subheader %}
<header> Create teacher</header>
{% endblock  %}


{% block content %}

    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

         <input type="button" class="btn btn-outline-dark" value="List of teachers" onClick='location.href="{% url 'teachers:list' %}"'/>
        <input type="submit" class="btn btn-outline-dark" value="Create">
    </form>
{% endblock  %}

teachers/templates/teacher_delete.html
{% extends 'base.html' %}


{% block title %}
    <title>Delete</title>
{% endblock  %}


{% block subheader %}
<header>Do you want to delete?</header>
{% endblock  %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        <input type="submit" class="btn btn-outline-dark" value="Yes" />
        <input type="button" class="btn btn-outline-dark" value="No" onClick='location.href="../"'/>

    </form>
{% endblock  %}

teachers/templates/teacher_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title>Edit teacher</title>
{% endblock  %}


{% block subheader %}
<header> Edit teacher</header>
{% endblock  %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="button" class="btn btn-outline-dark" value="List of teachers" onClick='location.href="{% url 'teachers:list' %}"'/>
        <input type="button" class="btn btn-outline-dark" value="Delete" onClick='location.href="{% url 'teachers:delete' teacher.id %}"'/>
        <input type="submit" class="btn btn-outline-dark" value="Save">
    </form>

{% include 'includes/groups-table.html' %}

{% endblock  %}

teachers/templates/teachers.html
{% extends 'base.html' %}


{% block title %}
    <title> Teachers list </title>
{% endblock  %}


{% block subheader %}
<header> Teachers list</header>
{% endblock  %}


{% block content %}
    <form>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">First name:</span>
            </div>
            <input type="text" class="form-control" placeholder="Enter first name" name="first_name"
                   aria-label="Username" aria-describedby="addon-wrapping">
        </div>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">Last name:</span>
            </div>
            <input type="text" class="form-control" placeholder="Enter last name" name="last_name" aria-label="Username"
                   aria-describedby="addon-wrapping">
        </div>

        <div class="input-group flex-nowrap mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">Place of work:</span>
            </div>
            <input type="text" class="form-control" placeholder="Enter place of work" name="job" aria-label="Username"
                   aria-describedby="addon-wrapping">
        </div>


      <input type="button" class="btn btn-outline-dark" value="Create" onClick='location.href="{% url 'teachers:create' %}"'/>
      <input type="submit" class="btn btn-outline-dark" value="Search"><p><hr>

        <h5>All list of teachers: </h5><p>

    </form>

<!--{{students|safe}}-->
{% if teachers %}

<table class="table table-hover" style="width:100%">
    <thead class="thead-dark">
    <tr>
        <th>Edit</th>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Place of work</th>
    </tr>
    </thead>
    {% for teacher in teachers %}
    <tr>
       <td><input type="button" class="btn btn-outline-dark" value="Edit" onClick='location.href="{% url 'teachers:edit' teacher.id%}"'/></td>
<!--       <td> <a href="{% url 'teachers:edit' teacher.id %}" >EDIT&ndash;&gt;</a></td>-->
       <td> {{ teacher.id }}</td>
       <td>{{ teacher.first_name }}</td>
       <td>{{ teacher.last_name }}</td>
       <td>{{ core.age }}</td>
       <td>{{ teacher.job }}</td>
    {% endfor %}
    </tr>
</table>
{% else %}
<p> List is empty </p>
{% endif %}

{% include 'includes/pagination.html' %}
{% endblock  %}