accounts/urls.py
from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordChangeView,
    AccountUpdateView
)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='change_password'),

]

core/urls.py
from core.views import index

from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),

]

groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls import url # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (
    # create_students,
    # delete_student,
    # edit_student,

    StudentCreateView,
    StudentDeleteView,
    StudentListView,
    StudentUpdateView,
    generate_students

)

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('generate/', generate_students, name='generate'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid_code>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid_code>', StudentDeleteView.as_view(), name='delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block title %}
    <title> LMS </title>
{% endblock  %}
{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock  %}
</head>
<body>


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
  <a class="navbar-brand" href="{% url 'core:index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'students:list' %}">Students <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
      </li>
        <li class="nav-item ">
        <a class="nav-link" href="{% url 'teachers:list' %}">Teachers</a>
      </li>
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--      </li>-->
    </ul>
   <ul class="navbar-nav ">
       {% if user.is_authenticated %}
        {% include 'includes/img.html' %}
           <li class="nav-item">
               <a class="nav-link" href="{% url 'accounts:profile' %}"> Profile </a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
           </li>

       {% else %}
           <li class="nav-item">
               <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
           </li>
       {% endif %}

    </ul>
  </div>
</div>
</nav>
{% endblock  %}


<link rel="stylesheet" href="{% static 'css/base_styles.css' %}" >
<div class="container">

    {% include 'includes/messages.html' %}


{% block header %}
<div class="border border-success shadow-lg p-3 mb-5 m-3 bg-white rounded text-center display-4">
{% block subheader %}
    <header>
    Headers
    </header>
{% endblock  %}
</div>
{% endblock  %}

{% block content %}
{% endblock  %}

</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% block link %}

{{ block.super }}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

<head>
    {% block title %}
        <title> Home page </title>
    {% endblock %}
</head>

{% block navbar %}
{% endblock %}

{% block header %}
    <header> Home page</header>
{% endblock %}

{% block content %}

<body>
    <div><br>
        <a href="{% url 'students:list' %}">Students list</a><br>
        <a href="{% url 'teachers:list' %}">Teachers list</a><br>
        <a href="{% url 'groups:list' %}">Groups list</a><br>
     </div>

{% endblock  %}
</body>
</html>